# GitHub Actions workflow for .NET application

name: .NET CI Pipeline

on:
  push:
    branches: 
      - develop
      - staging
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        if: github.ref == 'refs/heads/develop' 
        run: dotnet test --no-build --verbosity normal

  deploy:
    if: github.ref == 'refs/heads/staging' 
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x


      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: ./publish
