# GitHub Actions workflow for .NET application

name: .NET CI Pipeline

on:
  push:
    branches:
      - develop
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        if: github.ref == 'refs/heads/develop'  # Run unit tests only on develop branch
        run: dotnet test --no-build --verbosity normal

  integration-test:
    if: github.ref == 'refs/heads/staging'  # Run only on staging branch
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      - name: Run Integration Tests
        run: dotnet test --no-build --configuration Release --filter "Integration"
